destination: docs
title: Viktor Vsk
description: > # this means to ignore newlines until "baseurl:"
  Viktor Vsk | Personal Homepage
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: viktorvsk

# Author Settings
author: Viktor Vsk # add your name
author-img: avatar.jpg # add your photo
about-author: Software Developer
social-facebook: viktorvsk.ukraine
social-github: viktorvsk # add your Github handle
social-linkedin: viktorvsk
social-email: me@viktorvsk.com
social-stackoverflow: 2153409/viktor-vsk # https://stackoverflow.com/users/2153409/viktor-vsk
social-instagram: viktorvsk
social-skype: https://join.skype.com/invite/ufEWTkWLfJHQ
gpg-fingerprint: B933 9AAF E55A 63EF 6E04  C0A9 C8A6 A9F5 EFE5 5F72

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
include: [".well-known"]
