title: Viktor Vsk
description: > # this means to ignore newlines until "baseurl:"
  Viktor Vsk | Personal Homepage
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: viktorvsk

# Author Settings
author: Viktor Vsk # add your name
author-img: avatar.jpg # add your photo
about-author: Software Developer
social-twitter: viktorvsk
social-facebook: viktorvsk.official
social-github: viktorvsk # add your Github handle
social-linkedin: viktorvsk
social-email: me@viktorvsk.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
